# Replace the text below to customize your site
site_name: HBO-ICT Digitale turn based multiplayer game
site_description: Documentatie voor Game Development project
site_author: <student naam>
copyright: Copyright <year> GD <student name here>

site_url: https://propedeuse-gd.dev.hihva.nl//
repo_url: https://gitlab.fdmci.hva.nl/propedeuse-hbo-ict/knowledgebase/student-knowledgebase

extra_javascript:
  - js/p5.min.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  palette:
     # Palette toggle for light mode
    - scheme: default
       # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
      primary: light blue
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
  font:
    # See available fonts at https://fonts.google.com/
    text: Open Sans
    code: Ubuntu Mono
  icon:
    logo: material/diamond
  favicon: images/diamond.svg
  features:
    - navigation.instant
    - content.code.annotate
    - navigation.sections
    - content.tabs.link

exclude_docs: |
  /TechnicalDocumentation/

plugins:
  - search
  - git-authors
  - mermaid2
  - awesome-pages
  - mkdocs-video
  - section-index
  - git-revision-date-localized:
      fallback_to_build_date: true
      # Read more: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/#enabled
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]
  - macros
  - autolinks

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details  
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
